### ISSUE TITLE
Suspicious Sand shows up as Sand

### ISSUE THREAD

**Issue by bernzrdo** [Snownee/Jade#250]
### Mod loader

Fabric

### Minecraft version

1.20

### Mod version

11.0.3

### Modloader version

Loader 0.14.21 + API 0.83.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Notice how I'm facing suspicious sand and it displays as "Sand".

![2023-06-08_18 46 05](https://github.com/Snownee/Jade/assets/27358071/2a3f1bdf-d372-4e71-ae87-0a77549a6a21)

**Comment by Snownee** [comment]
this is a feature

**Comment by bernzrdo** [comment]
could there be at least an option to turn it off? someone who has blurry vision and uses this mod to narrate which blocks are they looking at will never know the difference between suspicious sand and sand. this is not very accessible.

**Comment by Snownee** [comment]
I will soon add a detector to automatically turn it off. But an option? No. Because Mojang does not provide an option to highlight these blocks, doesn't it? But they can already solve it themselves by replacing the textures.

**Comment by bernzrdo** [comment]
just seems weird to install a mod that displays the name of the block I'm looking at and it fails to display suspicious sand 🤷 but wtv

**Comment by Snownee** [comment]
You can still see the real name in creative or spectator mode. Let me be clearer, I don't want people to use this mod to gain an apparently unnecessary advantage and it will make the game experience worse, even if it is the player's choice.

**Comment by milkev** [comment]
Id like to say that the value of the games experience is ultimately up to the player, and having config options allows for players to enjoy the game more. I personally would love to have suspicious blocks displayed to me, and I understand that it would give me an "unnecessary" advantage, but they arent a block thats trying to disguise themselves super well like infested blocks are. For me, it just helps me remind me what the block is (Most of the reason I have jade installed). Much less for someone like the poster here, who has trouble identifying blocks by texture.
If you want, you could make it controlled by the server. So clients joining vanilla servers, or servers with it disabled, wont be able to see that it is a suspicious block. Thus removing any advantage over other players on the server. I agree that everyone should be on a level playing field.

Understandable if you still dont want to add it as a config, its your mod after all. Just wanted to share my opinion on the matter.

**Comment by Nightwolf3218** [comment]
I can appreciate your desire to keep things fair, but not displaying this is not preventing any type of advantage.  You can literally use the F3 menu to see that you are looking at suspicious sand or gravel instead of normal sand or gravel.  I could understand if this wasn't being shown in the F3 menu that you would feel this way.  Just like all the other blocks, you can technically use the F3 menu to see what block you are looking at, and to me the idea of this mod is just to make that process easier.  Technically these suspicious blocks have slightly different textures, however there are folks like me that suffer from visual impairments that make noticing these differences much more difficult and having the ability to more easily check if the block is one to brush via the mod instead of trying to use the F3 menu would be a tremendous help, especially when trying to do this at the bottom of the ocean.  Personally, I think that there should at least be an option to show this information.  As I stated above, this would not really provide any advantage to a player that they wouldn't also get by using the F3 menu to check what block they are looking at and would help those of us with visual impairments actually have a fair chance at finding these types of blocks against those that have better vision and can notice the small differences in textures.

This is just my opinion on the matter, and I do love the mod overall, but find this aspect a bit annoying and less than helpful.  Unfortunately, I haven't found any other mod that does this that has been updated for 1.20.2 for Fabric which is why I am instead trying to make a case for at least making it a player selectable option.

**Comment by electricsteve** [comment]
I would like to have this too, it's really irritating. Even if it's a config that allows server admins to let players use it.

**Comment by OutbackCatgirl** [comment]
> You can still see the real name in creative or spectator mode. Let me be clearer, I don't want people to use this mod to gain an **apparently unnecessary advantage**  and it **will make the game experience worse,** even if it is the player's choice.

I'm sorry but this is a godawful, wrong, and hypocritical excuse to lean on given the loot table for archaeology is mostly cosmetic and it's an incredibly rare block that does not convey any real advantage or "ruin the game". Have you SEEN the loot tables for suspicious gravel? If you just don't want to implement it because it's a pain in the butt to program in, that's perfectly reasonable to me and I would absolutely respect that stance here if it was your stated position, but your stated reasoning is complete hogwash and bears no resemblance to reality. Suspicious gravel is not some meta-breaking block and quite frankly you've lost me completely with this logic. 

Forcing your own value judgements on players artificially based on this logic is hypocritical given things like trap chests are fully marked by Jade as such. It's so arbitrary. How is suspicious gravel not being labelled in jade any more of a gameplay advantage than being able to tell when a chest is trapped? It's complete nonsense, i'm afraid. Surely you have a better reason in mind than that? 

In the end it is your mod and your decision to make and far be it from me to change your mind, but I would like it to be known that in my opinion it is a really weird hill to die on and a decision based on flawed logic and awful assumptions. I do not expect to have convinced you of this, but please at least consider thinking about what i've said without dismissing it out of hand for criticising your decision.

**Comment by milkev** [comment]
> Forcing your own value judgements on players artificially based on this logic is hypocritical given things like trap chests are fully marked by Jade as such. It's so arbitrary. How is suspicious gravel not being labelled in jade any more of a gameplay advantage than being able to tell when a chest is trapped? It's complete nonsense, i'm afraid. Surely you have a better reason in mind than that?

oh, no its its actually explicitly coded out of showing up in jade. its not even hard to change, if it was something that actually mattered to me id probably just fork the project and change it myself for personal use. if you set this function to return false it would probably do the trick just fine. https://github.com/Snownee/Jade/blob/1d653551008d8c3c4aea0cb1824b6613f6477baa/src/main/java/snownee/jade/JadeClient.java#L308

**Comment by lunaynx** [comment]
Yeah, this is ridiculous. If you really wanted to, you could simply condition masking infested blocks on Reduced Debug Info being enabled. But masking Suspicious Gravel and Suspicious Sand is just ridiculous regardless – they have noticeably distinct textures from normal Gravel and Sand in vanilla.
