### ISSUE TITLE
[1.20.1] Narrator has no indicator its on, causing confusion when trying to disable 

### ISSUE THREAD

**Issue by EvergreenSystems** [Snownee/Jade#282]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.1.4

### Modloader version

47.1.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

The narrator does not have a tooltip (to my knowledge) that indicates that it is on. I ran into the situation where I accidentally enabled it via keybind, and then spent half an hour trying to figure out what narrator was on as I did not realize Jade had such a function and it was causing significant lag in my world. A tooltip on the indicator at the top would be very helpful to prevent such confusion in the future.

Appreciate the work that goes into this mod, its an amazing accessibility feature and I love the revamp the config got recently. Cheers!

**Comment by Snownee** [comment]
By default, the narrator is in PREESS mode, i.e., it only narrates once when the key is pressed. You have to first change it to TOGGLE mode in the configuration screen, and then press the key accidentally to be in the situation you are talking about.

For the lag issue you mentioned, it's been fixed in the latest version.

**Comment by EvergreenSystems** [comment]
hm, you seem to be correct (I'm not sure how it ended up in toggle mode). Regardless, some sort of indicator would be nice as it evidently _can_ be triggered by mistake. Again, thanks for the work thats put into this mod, its amazingly useful
