### ISSUE TITLE
Add a way to disable smoothing for specific ProgressElements

### ISSUE THREAD

**Issue by Technici4n** [Snownee/Jade#384]
### Mod loader

NeoForge

### Minecraft version

1.20.4

### Mod version

doesn't matter

### Modloader version

doesn't matter

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Would be nice to be able to disable smoothing for specific progress bars, maybe in the `ProgressStyle`. It doesn't play nicely with a "looping" progress bar that I am trying to implement in Modern Industrialization.

**Comment by Technici4n** [comment]
Hmm, the smoothing is actually needed given that Jade only syncs every 5 ticks. Could there be a way to declare a progress bar as "increase only", such that decreases are treated as "wrapping around", and smoothly interpolate until the end of the progress bar? There seems to be a similar boolean already, but in my testing it didn't work well either.

**Comment by Snownee** [comment]
The problem is there is no way to know if a decrease is "wrapping around" or "beginning of a new loop". The similar boolean you mentioned means if the progress drops in the next tick, it will immediately play a transition animation to 100% and then go to the current value.

If you don't want the smoothing, you can use `ProgressElement.tag(null)` to disable it.

**Comment by Technici4n** [comment]
OK, `canDecrease` does exactly what I need. It just didn't work for me with hot reloading because of the global variables. Thank you! :)
