### ISSUE TITLE
[Suggestion] Display mode: Spyglass

### ISSUE THREAD

**Issue by Kirisoup** [Snownee/Jade#420]
### Issue description

Add a new display mode where overlay is shown when using a spyglass.

I've implemented this in 1.20.1 https://github.com/Kirisoup/Jade/commit/579fe579049e81f0367be9d3e85d6d2e6338db05 for my personal use, my implementation might be bad but I think this is a neat feature to add.

Sorry I am very new to mc modding ;_;

**Comment by Snownee** [comment]
There are some problems with your changes because the server side will refuse to fetch data if the target is too far from the player. Also you should only multiply the result of `mc.gameMode.getPickRange()` by 3, not the whole expression.

I will merge this feature if you can resolve these problems and open a PR.

**Comment by Kirisoup** [comment]
In that case should I commit to the main branch instead?

**Comment by Snownee** [comment]
Ideally yes because I don't want to bother porting things so I prefer to only maintain it on 1.21
