### ISSUE TITLE
[SUGGESTION] Add detail in tooltip when Silk Touch is used

### ISSUE THREAD

**Issue by Davsennn** [Snownee/Jade#428]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

15.1.3

### Modloader version

Fabric Loader 0.15.11 + API 0.100.4

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

When looking at a block that drops different items wether or not Silk Touch is used, add a detail in the tooltip that displays what of the two will be dropped when using the tool/item held in the main hand. E. g. if you are looking at bookshelves without Silk Touch, you will see that books will be dropped instead of the bookshelf item. Note that using a not fitting tool with Silk Touch will also work, so breaking bookshelves with a Silk Touch Pickaxe will drop the bookshelf item instead of books.

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.

**Comment by RubyRezal** [comment]
I would also like really appreciate some indication that a block requires silk touch to drop as a block. Just getting a green checkmark for right tool to efficiently break the block is kind of frustrating if the goal is to collect it.  Unwittingly destroying a block because an information addon indicated it was ok to break is a bit annoying.

Chiseled Bookshelves require silktouch... why...
